swcarpentry/board

committee_roles.md

just realized this was never made public... was supposed to be included in the call for steering committee nominations (that was the point).
can we add this here, @gvwilson , @DamienIrving ?

adds committee roles

---

subcommittees/subcommittees.md

Moves the subcommittees list into the public.

fixes #18 ? @jiffyclub, can you merge?

---

minutes/2014-12-02.md
minutes/2015-02-03.md
minutes/minutes-2015-02-12.md
minutes/minutes-2015-02-19.md
minutes/minutes-2015-02-26.md
minutes/minutes-2015-03-12.md

Details in the commit messages.

Copy-edits for the minutes (committee typos, dangling parents, etc.)

---

workshops.md

Adjusting wording on use of money from workshops for companies

---

subcommittees/mentoring/minutes-2015-04-10.md

@BillMills, @chendaniely, @karinlag and @mckays630 Could you give a +1 if you are OK with this?

Add minutes of Mentoring Subcommittee on 2015-04-10

---

subcommittees/assessment/minutes-2015-05-04.md

Meeting notes from 2015-05-04

---

subcommittees/assessment/minutes-2015-05-04.md

@gvwilson created the assessment repo under swc and this PR fixes the links that need to be updated.

update links in minutes to reflect repo change

---

subcommittees/mentoring/minutes-2015-08-07.md

@ttimbers and @k8hertweck Could you review this?

Add minutes from 2015-08-07 mentoring subcommittee meeting

---

subcommittees/mentoring/minutes-2015-09-21.md

Adding meeting minutes for Sept 21

---

subcommittees/mentoring/minutes-2015-10-05.md

@k8hertweck could you review this? The notes are available at https://old.etherpad-mozilla.org/scf-mentoring.

Add minutes of mentoring subcommittee at 2015-10-05

---

subcommittees/subcommittees.md

Add Former members section for subcommittee

---

subcommittees/mentoring/minutes-2015-11-30.md

**Don' t merge it yet.** Need to clean the markdown.

Add minutes of mentoring subcommittee meeting on 2015-11-30

---

strategy/strategic_plan.md

Moving the strategic plan over. @katyhuff to merge and announce.

Adding strategic plan

---

strategy/strategic_plan.md

With:
$ sed -i 's/  *$//' strategy/strategic_plan.md
In particular, this will remove a <br> from the current rendering:
$ curl -s https://github.com/swcarpentry/board/blob/master/strategy/strategic_plan.md | grep -B1 'capture learner outcomes'
in scientific research, but our current assessment system does not sufficiently<br>
capture learner outcomes.</p>

strategy/strategic_plan.md: Strip trailing whitespace

---

subcommittees/mentoring/guidelines_for_checkout_discussion_sessions.md

This addresses issue #72 .
Can especially @gvwilson and @rgaiacs have a look? All comments and thoughts welcome.

Starting on writing some guidelines for checkout discussion sessions

---

README.md

Fix broken links, add missing dates, consistent order from oldest to newest

Fix links to minutes in README.md

---

README.md
maintainers.md

I'm not sure if this is the right location for this material, but it can start here...
Comments welcome!

rough draft of maintainer responsibilities and transition checklist

---

subcommittees/mentoring/checklists-discussion-sessions.md
subcommittees/mentoring/procedure-debriefing-session.md
subcommittees/mentoring/procedure-discussion-session.md

Adding a checklist for hosts (and the organizer), archiving old procedure.  
Once merged, will add the link to the checklist to the discussion session etherpad.

Discussion session additions

---

subcommittees/mentoring/guidelines_for_checkout_discussion_sessions.md

Adding information from #72 and archiving these discussion guidelines since we are no longer using this for the checkout process.

archiving old checkout discussion sessions

---

subcommittees/mentoring/minutes/minutes-2016-08-29.md

minutes from aug 29 mentoring meeting

---

subcommittees/mentoring/checklists-discussion-sessions.md
subcommittees/mentoring/procedure-discussion-session.md

Adding notes about splitting sessions, and how to indicate that a trainee is checking out.

Discussion session update

---

governance.md

This PR includes the current public-facing governance rules with the addition of the following proposed amendment:
"Following an election, the new Steering Committee will meet jointly with the previous Steering Committee for no less than 60 days. For meetings during the first 30 first days, the new SC will not have voting privileges. After 30 days, voting privileges are transferred to the new SC."
The community election for this amendment will be held October 10-14.

Amendment for Steering Committee transition procedures.

---

subcommittees/mentoring/minutes/minutes-2016-12-12.md

very very late mentoring minutes from last year.

december meeting minutes

---

subcommittees/maintainers/exercises-and-solutions.md
subcommittees/maintainers/handover.md
subcommittees/maintainers/installation-instructions.md
subcommittees/maintainers/release-process.md
subcommittees/maintainers/revised-template.md

One placeholder, others still need editing, one more to come.

Decisions of lesson maintainers committee

---

TaskForces/2017-CarpentryCon/minutes/2017-03-06.md

Create 2017-03-06 taskforce minutes

---

subcommittees/mentoring/minutes/minutes-2017-03-27.md

Sorry for the delay in pushing these. Soon after the meeting I spilled water over my laptop, and I've only just dared to switch it back on again!

added minutes from March 2017 meeting

---

subcommittees/trainers/minutes/2017-04-06-discussion.md

Create 2017-04-06-discussion.md minutes

---

subcommittees/mentoring/checklists-discussion-sessions.md

new google doc link

---

governance.md

This will need review, and there are additional amendments forthcoming. These will be presented to the Advisory Counsel after the Steering Committee's ratification.

add amendments from 2016 in-person meeting

---

subcommittees/mentoring/minutes/minutes-2017-05-22.md

minutes from the 22-May-2017 mentoring subcommittee meeting

May 2017 meeting

---

minutes/resolutions.md

In an attempt to make the board's actions more transparent, I've gone through and added all the motions passes since March 2017

Added motions passed by 2017 committee

---

TaskForces/2018-CarpentryCon/minutes/2017-06-04.md

Create 2017-06-04.md minutes for CarpentryCon

---

minutes/resolutions.md

I went through all the old meeting minutes and pulled out brief summaries of all the past motions.

added resolutions from 2016 and 2015

---

subcommittees/trainers/README.md

Updated the readme to direct site visitors to the trainer agreement. 
cc @ErinBecker

updated Trainer README

---

TaskForces/2018-CarpentryCon/README.md

- I've changed the README.md
- I've copied the minutes files to the new CarpentrCon repo
- I *cannot* delete the minutes files / folder here. Someone should be able to do so...

Changed the README to point to CarpentryCon repo

---

subcommittees/mentoring/files/pre_workshop_email.txt

Updated some wording to reflect Carpentries merge

reflect Carpentries in email

---

subcommittees/mentoring/onboarding-document.md

Create a markdown file in swcarpentry github mentoring committee folder to be shared
Google doc is created but want to create markdown in swcarpentry github

Create mentoring committee onboarding doc

---

subcommittees/mentoring/minutes/minutes-2017-08-28.md

The minutes from yesterdays meeting. If you prefer, I can re-submit after we've migrated to the new carpentries repo?

August 2017 meeting

---

governance.md

This would make @rgaiacs' proposal from [here][1] lawful.
[1]: https://github.com/swcarpentry/board/blob/13037e523e1ea5c7b1612582ff252b37f92018a1/minutes/minutes-2017-01-04.md#motion-2017-01-041

governance: Adapt Steering Committee rules for low-candidate elections
